namespace: boutique

image:
  registry: vrushacr777.azurecr.io
  tag: "4b2402e42bcfd44c935a30da296cdd52808b975c"

replicas:
  frontend: 1
  cartservice: 1
  productcatalogservice: 1
  currencyservice: 1
  paymentservice: 1
  shippingservice: 1
  checkoutservice: 1
  recommendationservice: 1
  emailservice: 1
  adservice: 1
  loadgenerator: 1
  redisCart: 1

autoscaling:
  frontend:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  cartservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  productcatalogservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  currencyservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  paymentservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  shippingservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  checkoutservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  recommendationservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  emailservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  adservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  loadgenerator:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70

  redisCart:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 70

shoppingassistantservice:
  enabled: false

services:
  frontend:
    port: 8080

  cartservice:
    port: 7070

  productcatalogservice:
    port: 3550

  currencyservice:
    port: 7000

  paymentservice:
    port: 50051

  shippingservice:
    port: 50050

  checkoutservice:
    port: 5050

  recommendationservice:
    port: 8081

  emailservice:
    port: 8080

  adservice:
    port: 9555

  redis:
    port: 6379

redis:
  tag: "4b2402e42bcfd44c935a30da296cdd52808b975c"