sonar.projectKey=Vrush-777_boutique-app_Microservices-Demo
sonar.organization=vrush-777

sonar.projectName=boutique-app_Microservices-Demo
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/node_modules/**,**/.venv/**,**/venv/**,**/build/**,**/dist/**
sonar.test.inclusions=**/*_test.go,**/*_test.py,**/*.test.js,**/test_*.go
sonar.cpd.exclusions=**/node_modules/**,**/.venv/**

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true