apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: {{ .Values.namespace }}

spec:

  replicas: {{ .Values.replicas.frontend }}

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      containers:

      - name: frontend

        image: "{{ .Values.image.repository }}/frontend:{{ .Values.image.tag }}"

        ports:

        - containerPort: 8080

        env:

        - name: PORT
          value: "8080"

        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"

        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"

        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"

        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"

        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"

        readinessProbe:

          httpGet:
            path: /
            port: 8080

          initialDelaySeconds: 10

          periodSeconds: 10


        livenessProbe:

          httpGet:
            path: /
            port: 8080

          initialDelaySeconds: 30

          periodSeconds: 20