name: Azure DevSecOps GitOps Pipeline

on:
  push:
    branches: 
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  security-events: write

jobs:

  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest

    outputs:
      jump_vm_ip: ${{ steps.jump-ip.outputs.jump_ip }}

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Azure Login
      uses: azure/login@v2

      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      shell: bash
      run: |
        SSH_PUBLIC_KEY=$(cat ~/.ssh/jump-vm.pub)
        terraform plan \
          -var-file=terraform.tfvars \
          -var "jump_vm_ssh_public_key=${SSH_PUBLIC_KEY}" \
          -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Get Jump VM Public IP
      id: jump-ip
      run: |
        JUMP_IP=$(terraform output -raw jump_vm_public_ip)
        echo "Jump VM Public IP: $JUMP_IP"
        echo "jump_ip=$JUMP_IP" >> "$GITHUB_OUTPUT"
      
    - name: Wait for Azure RBAC propagation
      shell: bash
      run: |
        echo "Waiting for Jump VM RBAC assignments to propagate..."
        sleep 120

  security:
    name: DevSecOps Security Scans
    needs: terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: fs
           scan-ref: .
           format: table
           severity: HIGH,CRITICAL
           exit-code: 0

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main

        with:
          project: boutique-app
          path: .
          format: HTML
          out: reports

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Vrush-777_boutique-app_Microservices-Demo
            -Dsonar.organization=vrush-777

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
   
  build:
    name: Build & Push Images
    needs: security
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        service:
          - frontend
          - cartservice
          - productcatalogservice
          - currencyservice
          - paymentservice
          - shippingservice
          - emailservice
          - recommendationservice
          - adservice
          - checkoutservice
          - loadgenerator
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Login to ACR
      run: |
        az acr login \
          --name vrushacr777

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: src/${{ matrix.service }}
        file: docker/${{ matrix.service }}/Dockerfile
        push: false
        load: true

        tags: |
          ${{ matrix.service }}:scan

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ matrix.service }}:scan
        format: table
        severity: HIGH,CRITICAL
        exit-code: 0

    - name: Tag Images
      run: |
        docker tag \
        ${{ matrix.service }}:scan \
        ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest

        docker tag \
        ${{ matrix.service }}:scan \
        ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }}

    - name: Push Latest
      run: |
        docker push \
        ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest

    - name: Push SHA
      run: |
        docker push \
        ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }}

    - name: Finished
      run: |
        echo "${{ matrix.service }} pushed successfully."

# ====================================================================

  redis-image:
    name: Push Redis Image
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Login to ACR
      run: |
        az acr login \
        --name vrushacr777
    - name: Pull Redis Image
      run: |
        docker pull redis:7-alpine
    - name: Tag Redis Image
      run: |
        docker tag \
        redis:7-alpine \
        ${{ secrets.ACR_LOGIN_SERVER }}/redis-cart:latest

        docker tag \
        redis:7-alpine \
        ${{ secrets.ACR_LOGIN_SERVER }}/redis-cart:${{ github.sha }}
    - name: Push Redis Image
      run: |
        docker push \
        ${{ secrets.ACR_LOGIN_SERVER }}/redis-cart:latest

        docker push \
        ${{ secrets.ACR_LOGIN_SERVER }}/redis-cart:${{ github.sha }}

    - name: Redis completed
      run: |
        echo "Redis image pushed successfully."

  update-values:
    name: Update Helm Image Tag
    needs:
      - build 
      - redis-image
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Helm Image Tag
      run: |
        sed -i -E "s|^  tag:.*|  tag: \"${GITHUB_SHA}\"|" boutique-helm/boutique/values.yaml

    - name: Verify Helm Image Tag
      run: |
        echo "Updated image tags:"
        grep -E "^[[:space:]]+tag:" boutique-helm/boutique/values.yaml
    
    - name: Verify values.yaml
      run: |
        echo "===== Updated values.yaml ====="
        cat boutique-helm/boutique/values.yaml

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit Changes
      run: |
        git add boutique-helm/boutique/values.yaml
        git diff --cached --quiet || \
        git commit -m "Update image tag to ${GITHUB_SHA}"

    - name: Push Changes
      run: |
        git push origin main

  deploy:
    name: Deploy Boutique from Jump VM
    needs:
      - terraform
      - update-values
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Prepare SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.JUMP_VM_SSH_PRIVATE_KEY }}" > ~/.ssh/jump-vm
          chmod 600 ~/.ssh/jump-vm

          ssh-keygen -y -f ~/.ssh/jump-vm > ~/.ssh/jump-vm.pub

          echo "SSH public key generated successfully."

      - name: Test SSH Connection
        shell: bash
        run: |
          ssh -i ~/.ssh/jump-vm \
            -o StrictHostKeyChecking=yes \
            azureuser@${{ needs.terraform.outputs.jump_vm_ip }} \
            "echo 'SSH connection to Jump VM successful'"

      - name: Copy deployment files to Jump VM
        shell: bash
        run: |
          ssh -i ~/.ssh/jump-vm \
            azureuser@${{ needs.terraform.outputs.jump_vm_ip }} \
            "mkdir -p /opt/deploy/boutique"

          scp -i ~/.ssh/jump-vm \
            -r boutique-helm \
            azureuser@${{ needs.terraform.outputs.jump_vm_ip }}:/opt/deploy/boutique/

          scp -i ~/.ssh/jump-vm \
            scripts/deploy-boutique.sh \
            azureuser@${{ needs.terraform.outputs.jump_vm_ip }}:/opt/deploy/

      - name: Deploy Boutique from Jump VM
        shell: bash
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          ssh -i ~/.ssh/jump-vm \
            azureuser@${{ needs.terraform.outputs.jump_vm_ip }} \
            "chmod +x /opt/deploy/deploy-from-jump.sh && \
            AZURE_SUBSCRIPTION_ID='${AZURE_SUBSCRIPTION_ID}'\
             bash /opt/deploy/deploy-boutique.sh"