name: Deploy to AKS

on:
  push:
    branches: [main]
    paths:
      - 'helm-chart/**'
      - 'microservices-extra-kube-manifests/**'
      - '.github/workflows/deploy-aks.yaml'
  workflow_dispatch:

permissions:
  contents: read

env:
  NAMESPACE: boutique-app
  RELEASE_NAME: onlineboutique
  RESOURCE_GROUP: AZET-RG-Daas-Platform
  CLUSTER_NAME: ppowar-aks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CLUSTER_NAME }} \
            --admin \
            --overwrite-existing

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Create Namespace
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.RELEASE_NAME }} ./helm-chart \
            --namespace ${{ env.NAMESPACE }} \
            --values ./helm-chart/values.yaml \
            --values ./helm-chart/values-aks.yaml \
            --wait \
            --timeout 5m

      - name: Apply Ingress
        run: |
          kubectl apply -f microservices-extra-kube-manifests/ingress-aks.yaml

      - name: Print App URL
        run: |
          echo "App is reachable at: http://20.75.253.122"
